name: Verify code style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          sudo apt update && apt install -y --no-install-recommends cmake gcc clang clang-tidy clang-format make

      - name: Run clang-format
        run: |
          bash -c "./scripts/run_format.sh verify"
