name: Run library tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          apt update && apt install -y --no-install-recommends cmake gcc clang clang-tidy clang-format make

      - name: Run tests
        run: |
          bash -c ./scripts/run_tests.sh
